### ISSUE TITLE
Feature Request: Set decimal places

### ISSUE THREAD

**Issue by ika-musuko** [emavgl/oinkoin#10]
I live in a country (Japan) that typically doesn't use "decimals" or "cents" in the currency. Everything is just whole numbers.

So seeing values like e.g. "947.00" and "12345.00" all the time instead of just "947" and "12345" is visual noise in my case.

I would like some setting where I can configure the amount of decimal places shown in the app. Or at least be able to turn off the decimal places and only show whole values.

**Comment by emavgl** [comment]
Hello, thanks for the feedback. In which language do you have your smartphone?

**Comment by emavgl** [comment]
Hi @ika-musuko, I have just pushed a new version 1.0.23 with the option to select the number of decimal digits. You can find that option in the customization page. I am closing this issue but you should be able to comment for further feedback. I'd appreciate if can rate the app on the Play Store or just sharing it with your friends. Have a nice day! :)

**Comment by ika-musuko** [comment]
Thanks for the quick update @emavgl! Works great and looks as expected.

My phone is set to Japanese, though I believe Oinkoin does not support Japanese so I just see the English user interface. This is fine by me, but I could provide a (starting point) for a Japanese translation if you want. (And then hopefully a native Japanese person can come and correct it 😂)

Gave you a good rating in the Play Store btw (I initially downloaded the app from F-Droid though lol)

**Comment by emavgl** [comment]
Thanks for checking and for the rating, appreciated :) I am totally not familiar with Japanese language but you are more than welcome in contributing by creating a PR. Supporting a new language should be quite easy (if the UI does not have to change to support it). You can do it just by changing the i18n files and adding a new translation for each string in these files.

**Comment by nizarus** [comment]
Hi, please consider to add the possibility to get 3 decimals. Here in Tunisia we use that.

**Comment by emavgl** [comment]
Hi @nizarus, thanks for pointing this out. I'll take it in mind when reworking the currency locales soon!

**Comment by emavgl** [comment]
Hi @nizarus,

Thanks again for the suggestions. I have just released the version with a new system for visualizing the amount. You can also choose 3 decimals now. 

I would be happy if you can give it a try: https://github.com/emavgl/oinkoin/releases/tag/1.0.25

It may take some time before it arrives at the Google Play Store and even more for F-droid.

Have a nice day,
Emanuele

**Comment by nizarus** [comment]
Hi @emavgl,
Tested and it's OK.
Keep the good work.
