### ISSUE TITLE
[BUG] March is shown as April in the records view

### ISSUE THREAD

**Issue by dicamarques14** [emavgl/oinkoin#100]
In march, if I go to open the records graph view (pie chart icon) it shows April on top
![image](https://github.com/emavgl/oinkoin/assets/461708/65760946-a71a-4935-9d6a-18c402d6df21)

**Comment by emavgl** [comment]
True. Thanks for reporting, I'll fix it asap.

**Comment by emavgl** [comment]
Should be fixed with https://github.com/emavgl/oinkoin/releases/tag/1.0.54 - I am closing the issue, but feel free to comment or re-open the issue if the problem persist.
