### ISSUE TITLE
feature request: display total balance

### ISSUE THREAD

**Issue by hakaishi** [emavgl/oinkoin#106]
Right now I can see only the balance of the current month or a specified date span. But I'd also like to know what is left on my bank account. For this a total balance display over all entries would be needed.

I think this is related to #69.

Btw. I really love your app. 👍

**Comment by emavgl** [comment]
Hi there,

Thanks for opening the issue. I am currently working on this feature but it may take some time :)

**Comment by emavgl** [comment]
Hi there, I have added this feature in https://github.com/emavgl/oinkoin/releases/tag/1.0.58
If you now go to Settings > Customization you will find a setting where you can set the data interval for the homepage. 

Three options are available:hi
- Current month (the default option)
- Current year
- All records 

I am closing this issue, but feel free to try this feature, comment or re-open the issue if needed. Have a nice day!

**Comment by hakaishi** [comment]
Very nice! Thank you!

If I set it to "all records" I can reset the interval settings from the top menu (calendar) icon.  
But if I don't sell "all records" in the settings, then there is no such option.

I think it might be a good idea to also add "all records" to this list (month, year, date range, +all records).
