### ISSUE TITLE
Cursor always jumps to end of text

### ISSUE THREAD

**Issue by jooooscha** [emavgl/oinkoin#110]
When editing the text for a record, you cannot go back in the text to correct a mistake because the cursor always jumps back to the end of the text.

Steps to reproduce:

1. Press the plus icon and select any category
2. Enter the amount of money
3. Enter the text
4. Move cursor to the left to correct typo
5. Try to correct typo
6. Cursor jumps back to end of text

Additionally, I have a similar problem with entering the amount of money.
In that field, I cannot even move the cursor, but I feel like that is intended.

Thanks for taking your time and doing all this work!

**Comment by emavgl** [comment]
Thanks for the comment. I'll have a look asap :)

**Comment by emavgl** [comment]
It should be fixed with https://github.com/emavgl/oinkoin/releases/tag/1.0.57 - please reopen the ticket or leave a comment if there is still anything not working. Thanks again for reporting.
