### ISSUE TITLE
Title suggestions interrupt input

### ISSUE THREAD

**Issue by hakaishi** [emavgl/oinkoin#112]
1. No longer able to type anything in asian languages that need "conversion". Japanese Hiragana input often needs to be converted into Katakana or Kanji. Same for Chinese input. Converting is no longer possible. As a work around, I need to type into the memo and then copy the text to the title. 
2. Deleting in any language needs hitting the back space button multiple times instead of holding it down. Deleting or correcting a word became complicated because of this.

These issues started in March when record suggestions were added in version 1.0.50.

**Comment by emavgl** [comment]
Hi, I'm sorry for the issue. How can I do such a "conversion" to test it out? And what's exactly the problem?

**Comment by emavgl** [comment]
You can also disable the title suggestions from the settings. Could you maybe try if that solves your issue?

**Comment by hakaishi** [comment]
https://github.com/emavgl/oinkoin/assets/1302663/900d1198-b5a2-4a3a-af75-fa8f15cf474f


https://github.com/emavgl/oinkoin/assets/1302663/0a9a86b9-2d84-4a85-a607-266d450aaa3f

You can see in the video how it should work when I type into the note input. Or on any random app like Markor (the other video).

Keyboard is the stock one on Pixel 7a with latest updates installed (Android 14).

Current version of Oinkoin is 1.0.56 from f-droid.

**Comment by emavgl** [comment]
Hi there, thanks again for reporting the issue and for uploading the videos.

I have the feeling the issue was related to this other issue https://github.com/emavgl/oinkoin/issues/110 which was solved in the recent release: https://github.com/emavgl/oinkoin/releases/tag/1.0.57

Could you please update and try it again?

Thanks :)

**Comment by hakaishi** [comment]
I confirm: In the new release the issue has been resolved! 

Thank you!
