### ISSUE TITLE
Unescaped commas in values

### ISSUE THREAD

**Issue by skiwichu** [emavgl/oinkoin#113]
The export button generates an invalid `records.csv`.

If you put a comma "`,`" into the field `Note`, then it generates an invalid csv. It would be nice to escape it with double quotes `"`at best. And please, don't forget double quotes are valid characters as well. Problably, escaping double quotes using doubling it `""` seems to be the most usual.

Thanks.

**Comment by emavgl** [comment]
Thanks for reporting. Will have a look!

**Comment by emavgl** [comment]
It should be fixed with https://github.com/emavgl/oinkoin/releases/tag/1.0.57 - please reopen the ticket or leave a comment if there is still anything not working. Thanks again for reporting.
