### ISSUE TITLE
Bug: broken value validation when editing an existing record

### ISSUE THREAD

**Issue by egglessness** [emavgl/oinkoin#12]
Hi Emanuele, I've just found this app on F-Droid and I'm considering of migrating all my data in Money Manager to this one. 
I like it very much!

During the initial testing (version 1.0.22), I noticed that when I try to edit an existing record and tap on the Save button (even without actually editing anything), the validator in the Value field says "Please enter a numeric value".

Unfortunately, I'm not familiar with Dart so I can't pinpoint the issue, however it would be great if you would find the time to fix this issue.

Cheers

**Comment by egglessness** [comment]
Okay, after some more testing it seems an issue related to how decimals are handled in the Italian locale.

When I edit the record, the value field is filled with a number using a comma as decimal separator, and this breaks the validator. If I tap on the field, it automatically switches to the decimal point separator and the validation succeeds.

**Comment by emavgl** [comment]
Hi @egglessness,

Thank you so much for using the app and for reporting the bug. You are absolutely right. Will fix asap. :)

**Comment by emavgl** [comment]
The bug fix is in the version [1.0.24](https://github.com/emavgl/oinkoin/releases/tag/1.0.24). At the moment, in that page, I have disabled the currency string in the user's locale and keep the international instead (with . as decimal separator). When I will have some more time, I'd like to add a proper support to user locales so to allow "," as separator as well. In the other pages, you will see no differences instead.

F-droid releases are pretty slow unfortunately. If you want to give it a try right now, you can download the .apk from the [Release page](https://github.com/emavgl/oinkoin/releases/tag/1.0.24) or Install the app from Google Play (which is faster in publishing updates). However, the .apk is signed differently, I don't know if you can update the version installed with F-droid. In case, always better to create a Backup file.

I am closing this issue, but feel free to comment! Thanks again!
