### ISSUE TITLE
Changing recurrence influences old instances

### ISSUE THREAD

**Issue by newhinton** [emavgl/oinkoin#123]
If i change a recurring expense, like rent, past instances are changing aswell. It would be nice if past occurences could keep their value, to keep a proper ledger.

Thanks!

**Comment by newhinton** [comment]
Sorry, but what do you mean by that?

If i only change the value, existing instances also change the value.
If i change the value and recurrence date,  existing instances change the value and the date.

Is it possible to edit a recurrent payment AND to keep old records intact?

**Comment by emavgl** [comment]
If you change the value and the date to a future date, the previous record should remain untouched. When the new date comes, the new recurrent records will have the new value.

**Comment by emavgl** [comment]
If you change the value and the date to a future date, the previous record should remain untouched. When the new date comes, the new recurrent records will have the new value.

**Comment by newhinton** [comment]
Sadly that only removes the old records completely...


Though, i like the idea of how that is supposed to work. Maybe this should be documented better? Another idea would be to immediately change the date to the next one according to the reccurence pattern, so that it always updates the next one, and not the past ones.

**Comment by emavgl** [comment]
It may be a bug. I'll try to create a video to check if this is case, because I can't replicate this on my side.

Changing the date of a recurrent pattern is equivalent to deleting the recurrent pattern and creating another one with the new date.

**Comment by emavgl** [comment]
Could you please have a look to this video?

https://1drv.ms/v/s!Aj7jAM1nltbampVpvQaJIwaJUMSjNQ

Seems working correctly...

**Comment by newhinton** [comment]
Huh, this is weird. Now it works as intended, but i am pretty sure before the entry was just gone. Maybe some weird race condition was going on where it just wasn't displayed yet, but as this is now working as intended, this can be closed.

I'd still like to see this feature get more prominent as it deserves to be, but that might be a different ticket.

Thanks for looking into it anyway!

**Comment by emavgl** [comment]
Thanks for reporting. In case you get another problem, please comment and I'll try to investigate further.
