### ISSUE TITLE
Allow selecting dates before 2018

### ISSUE THREAD

**Issue by sideeffect42** [emavgl/oinkoin#130]
As a user who has imported his records from another app via the JSON import, I'd like to be able to see them in Oinkoin.
Currently I can only see records from 2018 or later, because the date picker does not allow me to select earlier months/years.

Please update the date picker logic to either allow users to select any date or use the lower/upper bounds of records stored in the database.

**Comment by emavgl** [comment]
Will do. No real technical restrictions 👌

**Comment by emavgl** [comment]
Fixed in the last version.
