### ISSUE TITLE
Buttons for adding new categories are cut off

### ISSUE THREAD

**Issue by zebra-cmyk** [emavgl/oinkoin#134]
Hi,

thanks for the app, I've been using it for 4 months now.

On my device, the buttons for adding new categories are cut off at the right edge of the screen. Perhaps a shorter label or automatic line breaks would be useful here.

**Comment by emavgl** [comment]
Hi there, thanks for the creating the issue. Could you please upload a screenshot and add some information regarding your device? Model, Version of Android and if you have Increased the fonts, or zoomed out the system.

**Comment by emavgl** [comment]
Oh, I see. Since you probably now German better, could you reccomend a shorter translations for such text? It is probably too long, and I would change it rather than putting it in two lines or cutting it if possible.

**Comment by emavgl** [comment]
Done. The new version should have the new translations. Thanks for contributing. I am closing the issue but in case feel free to comment.
