### ISSUE TITLE
Feature request: Allow making "show records per" option permanent

### ISSUE THREAD

**Issue by evergreenbear** [emavgl/oinkoin#137]
Hi,
I have been using oinkoin for a couple months and really like it! The only inconvenience I've had is that I can't configure the app to always show records yearly instead of monthly. I have to re-set it to show everything from this year instead of the current month each time I open the app, which is not a huge deal but I would love to see the option to make this setting persist instead of resetting each time the app is closed.

**Comment by emavgl** [comment]
Hi, there is an option for it in the Preferences page. ![Screenshot_20240802_203929_Oinkoin Pro.jpg](https://github.com/user-attachments/assets/2d24c2dd-6110-4ba5-928d-496ac653baea)

Does it do the work?

**Comment by evergreenbear** [comment]
Hi, it does! I was not on the latest version, I guess at one point I installed the apk from the github so F-Droid wasn't notifying me of any updates. I am now on the latest version and I have this option. Thanks for helping me with this!
