### ISSUE TITLE
No confirmation with calendar

### ISSUE THREAD

**Issue by rudolfmu** [emavgl/oinkoin#138]
I love your app, as it only makes me push those buttons needed for the job to get done. That is what I consider professional 😀
Except when I add an entry in the past. Then the calendar window opens, I click a date, and must confirm. Almost always I do click the right date, no need to confirm. Else I can correct.
So if could remove that "OK",  I would be (even more) happy. If it is part some lib so be it.
BTW, I recommended your app to many friends, and they use it. Other apps they did not use, as those were to complicated. You really did a good and professional job making your app good for every day use.

**Comment by emavgl** [comment]
Hi, thank you so much for the nice words. I am happy you like the app and its usability 😊

Unfortunately I can't do much about the calendar, as you have anticipated, it is part of the Google library and I don't have the freedom to change it.

I am closing this ticket, but I promise I will keep in mind for future developments.

Thanks again for the feedback!

**Comment by r4dh4l** [comment]
Hi, is it possible to add a possibility change the month by tapping the current month/year in the head bar?
