### ISSUE TITLE
Yearly Repeat

### ISSUE THREAD

**Issue by asandikci** [emavgl/oinkoin#140]
There should be a yearly repeat

**Comment by emavgl** [comment]
Will add 👍

**Comment by emavgl** [comment]
Added with https://github.com/emavgl/oinkoin/releases/tag/1.0.67 - Closing the ticket, but feel free to comment if it does not work for you.

**Comment by asandikci** [comment]
Looks good, thx for quick reply and fix.

>  but feel free to comment if it does not work for you.

okay, I can test this feature and report any problem after one year later 😅

**Comment by emavgl** [comment]
If you really want to test it, you can set the recond date years in the past and seeing it repeatedly. But see you in a year then 😜
