### ISSUE TITLE
Wrong Keyboard invoked

### ISSUE THREAD

**Issue by h4ckerle** [emavgl/oinkoin#15]
Hey,
 first of all I have to say great app you are developing there!
However with the most recent update 1.0.24 via Fdroid it has become relatively hard to use. 
This seems to relate to the fix for #12 as now the correct decimal separator (,) is enforced for my locale (German) however the keyboard spawned presents a . as decimal separator which doesn't work anymore. Thus when entering a sum the quick way I end up with ridiculously high amounts 100x I actually spent.

**Comment by emavgl** [comment]
Hi @h4ckerle, I am happy you like the app and thank you for taking the time for the feedback. I have recently reworked the currency localization. Could you try out the new version https://github.com/emavgl/oinkoin/releases/tag/1.0.25 to see if it solves the issue?

Unfortunately it takes time time for F-droid to make the update available. Generally, if you want to get the very latest version,  you can use the Google Play version or download the .apk file from the Release page https://github.com/emavgl/oinkoin/releases/tag/1.0.25

If you switch between versions (F-droid, Apk from Github etc), make sure you do a Backup first. It should work fine, but better safe than sorry.

**Comment by nizarus** [comment]
Hi @emavgl,
I confirm this issue, French localization, with 1.0.25 version.

![Screenshot_2023-12-02-17-20-58-45_0f5c2f5270a23bdff84fc4b805035205](https://github.com/emavgl/oinkoin/assets/17108772/b742435b-1c96-45e0-b407-e082089580b4)

**Comment by emavgl** [comment]
Hi @nizarus,

I pushed the change in the new version 1.0.27 https://github.com/emavgl/oinkoin/releases/tag/1.0.27

With this version, if your decimal separator is `comma`, it will enable by default an option called `Overwrite the dot`. With this option enabled, when typing dot, it will type for you the comma instead. You can disable this option at any time from the Preference page. This option is not available if the dot is the decimal separator for your locale. However, a small tradeoff, in the editing page, it is not possible anymore the grouping of the digits.

Please, let me know if that helps :+1:

**Comment by emavgl** [comment]
Ah, got your point.

It could be an option, but I have chosen that keyboard because you have access to other symbols +, -, * etc, that you can use in the edit field.

For example, you can write 5 + 5 and it will be do the basic math for you.

While the keyboard you propose it is a bit limited. Maybe I can have those math symbols as buttons below the textbox... :/
