### ISSUE TITLE
Important: Oinkoin 1.0.67 from F-droid does not start. Do not update.

### ISSUE THREAD

**Issue by emavgl** [emavgl/oinkoin#151]
I don't know what the issue is. Seem just with F-droid build. I am trying to fix, but for now please do not update the app.

**Comment by emavgl** [comment]
From a log analysis it seems a problem related to: https://github.com/fluttercommunity/plus_plugins/issues/2391
which seem a build error and can get solved with a new rebuild. A new version 1.0.68 has been released (not on Google Play) and it will be on fdroid in about a week.

Now:
- You can wait for a new version in Fdroid to come up and hope that a rebuild solve the problem
- You can try to downgrade to 1.0.66. 
  - **Important:  the downgrade requires you to uninstall the app. When uninstalling the app, you will be prompt if you want to keep the data or not. If you want to keep the data, make sure to select the option when uninstalling. I have tried it twice and it seems keeping the data. But I would not call it 100% sure. Please be aware of the risks that data can get lost.**

  - Uninstall the current Oinkoin App. Make sure to select the option to keep the data.
  - Go to FDroid and open the Oinkoin page
  - All down, open the Versions tab
  - Install the version 1.0.66 manually
  - Do not update

![immagine](https://github.com/user-attachments/assets/68783715-0cfd-412c-83c7-a955bd1ee2e5)

Please, consider to do not use F-droid in the future, but get the latest apk via Obtanium. This allows faster update.

**Comment by emavgl** [comment]
Please, consider to do not use F-droid in the future, but get the latest apk via Obtanium or Google Play. This allows faster update.

**Comment by GhostShadow0316** [comment]
Ok I come here after it broke
I thought that was my problem
I will try to downgrade using adb
hope it'll work

would you like to add a automatic backup in the future btw

**Comment by emavgl** [comment]
I have disabled that version from F-droid https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15713 however it takes time to propagate, as usual with F-droid. Honestly, I just have bad experiences with F-droid, but it gives the app some visibility. 

Regarding the automatic backup: https://github.com/emavgl/oinkoin/issues/9

Which, given this last event, I plan to start soon.

**Comment by rudolfmu** [comment]
I downgraded and my data is intact.

**Comment by emavgl** [comment]
I am happy to hear you got your data back. Thanks for sharing your experience

**Comment by GhostShadow0316** [comment]
is the **Keep Data** option controllable for the developer? I haven't seen this option for a while

**Comment by emavgl** [comment]
It is an option the developer has to specify in the manifest https://developer.android.com/guide/topics/manifest/application-element#fragileuserdata

I can't explain why this has failed in some cases.

**Comment by iBabu007** [comment]
When it'll fixed. Please fixed it.
I can't downgrade my app.
Uninstall current version and previous version can't install

**Comment by emavgl** [comment]
@iBabu007 a possible fix is on the way on F-droid.

Another workaround, for technical people:

- Get the APK from F-droid of version 1.0.66.
- Follow this guide for the downgrade with ADB: https://www.repeato.app/how-to-bypass-install-failed-version-downgrade-error-in-android-adb-installations/

**Comment by iBabu007** [comment]
Hi, why i can't install any older version of this app??
![Screenshot_20240916-112024](https://github.com/user-attachments/assets/fec28e37-5243-4e84-a824-7ee6d2e71d15)

**Comment by emavgl** [comment]
Hi, I am not sure which version are you installing, but probably because you are trying to update a version from F-droid and one from Github or viceversa. The reason is that they are signed differently.

**Comment by iBabu007** [comment]
first i uninstall v 1.0.67 and then 
I try almost 5-6 older versions.but can't install it's any older versions.

**Comment by emavgl** [comment]
Make sure you download the ones from your phone CPU's architecture. It most likely is `arm64`

**Comment by luisgdev** [comment]
> first i uninstall v 1.0.67 and then I try almost 5-6 older versions.but can't install it's any older versions.

Same here, no luck installing from the phone. So I tried from `adb` and it worked.

**Comment by emavgl** [comment]
Thanks for trying. Another thought I have could be that the folder between two different version needs to be deleted. So if you want to switch between F-droid and Github version, let's say. The steps would be the following:

- Uninstall 1.0.67 F-droid keeping the data
- Installing 1.0.66 from F-droid
- Export backup
- Uninstalling the 1.0.66 from F-droid removing the data
- Installing Github version

**Comment by emavgl** [comment]
Hello, I saw the the Oinkoin 1.0.68 on F-droid is finally out. On my devices, it works again as expected. Could you please give it a try as well?

**Comment by MaelImhof** [comment]
I personally had the same issue, the new version (1.0.68) on F-Droid fixed it for me.

**Comment by emavgl** [comment]
As F-droid does not have anymore the faulty version 1.0.67 and the new version 1.0.68 opens as expected, I am closing this issue. Thank you for your help!
