### ISSUE TITLE
Feature: missing icon for "Barber" (scissors), ability to set custom icon images

### ISSUE THREAD

**Issue by Crystalwarrior** [emavgl/oinkoin#155]
Currently, some activities are missing from the icons for income/expenses. Additionally, there is no way to use custom icons.

I suggest adding that ability so the app can pull that icon from wherever the user specified and cache it.

A good resource of icons is https://www.svgrepo.com/

**Comment by emavgl** [comment]
The projects uses this set of icons: https://fontawesome.com/search?o=r&m=free
Feel free to create a pull request adding those you like. 
Additionally, I may think to use Emoji instead.
Custom icons are not possible because they don't have standard sizes, probably need some processing before, and they will be surely a problem for backups/restore.

**Comment by Crystalwarrior** [comment]
Emoji sounds good

**Comment by emavgl** [comment]
Will eventually implement. Thanks for the input.

**Comment by GhostShadow0316** [comment]
> The projects uses this set of icons: https://fontawesome.com/search?o=r&m=free Feel free to create a pull request adding those you like. Additionally, I may think to use Emoji instead. Custom icons are not possible because they don't have standard sizes, probably need some processing before, and they will be surely a problem for backups/restore.

what about let the user choose any icon from the website? is this doable?

**Comment by emavgl** [comment]
Not double because of this problem https://github.com/emavgl/oinkoin/issues/155#issuecomment-2352916036

**Comment by emavgl** [comment]
Emoji are now available and can be used instead of normal icons https://github.com/emavgl/oinkoin/releases/tag/1.0.71 - I am closing the issue. Thanks for your help!
