### ISSUE TITLE
Bug: App caps the display refresh rate to 60 Hz

### ISSUE THREAD

**Issue by adarsh1001** [emavgl/oinkoin#16]
Just noticed that the app caps the display refresh rate to 60 Hz even if 120 Hz is supported and forced on the device. Currently, Oinkoin is the only app that doesn't run at 120 Hz on my device.

![Screenshot_20231123-002404_1.png](https://github.com/emavgl/oinkoin/assets/8820038/bcbc37d5-c98b-467a-a41e-c0d4c58dba10)

Device: Nothing Phone (2)
OS: Android 13

Don't think it's a device specific issue, will let others confirm.

**Comment by emavgl** [comment]
Hi @adarsh1001, you have a good eye.

It seems to be an issue with Flutter. But there should be an easy fix https://pub.dev/packages/flutter_displaymode

I will try this package when I have a moment.

Which is the app you are using for checking the Hz of the apps?

**Comment by adarsh1001** [comment]
Hey @emavgl, so there's this setting in Android's Developer Options that shows the display refresh rate. At least on Android 13 it ought to be present, unless some OEM has disabled it 😅

![Screenshot_20231123-022746.png](https://github.com/emavgl/oinkoin/assets/8820038/1859ac77-fba9-4130-a432-aba8d0a10473)

**Comment by emavgl** [comment]
Found, thank you!

For me it shows 120! 🙄 Maybe on selected devices it needs to be forced to run at that frequency...

**Comment by adarsh1001** [comment]
Hmm interesting. That's the main problem with Android right, each OEM does things differently 😅

I actually have zero experience when it comes to frontend/mobile development 🥲 You'll need to guide me or if you can make the changes, I can test them out.

**Comment by emavgl** [comment]
I would be happy to on-board you, but unfortunately I don't have much time. But if you want to start learning flutter, it could be a good start. Otherwise, I'add this task in my to-do list with low priority :)

**Comment by emavgl** [comment]
Hi @adarsh1001, could you try if this version works for you?
[Uploading app-arm64-v8a-pro-release.zip…]()

**Comment by adarsh1001** [comment]
Hey @emavgl, works perfect! Thanks.

**Comment by emavgl** [comment]
Fix in the new version https://github.com/emavgl/oinkoin/releases/tag/1.0.26
