### ISSUE TITLE
Proposal: Add Test Automation with Appium (Java)

### ISSUE THREAD

**Issue by raulexacon** [emavgl/oinkoin#162]
Hi, I saw that the project is open to contributions, and I was wondering if it might be useful to add some Test Automation using Appium with Java. I noticed that the code is mostly written in Dart, but I’d still like to contribute by improving the automated testing part. Do you think this would be a useful direction for the project? Let me know if you think this could help!

**Comment by emavgl** [comment]
Hi, you are welcome to give it a try and write some tests. For sure, more tests do not harm. However, I am the only contributor to this project, and I am not sure if I am able to keep-up in maintaining / writing those tests. So it is up to you deciding if you want to make some experience and trying Appium with a flutter project.

**Comment by emavgl** [comment]
I think it makes sense to add the ID where necessary for the sake of the tests. Maybe you can give it a try in the scope of your PR?

**Comment by raulsorrentino** [comment]
I’m using Flutter version 3.22.1 and experiencing some issues replicating the project environment, especially with the build in build.gradle. Could you let me know which JDK version you’re using and any other key settings that might be necessary?

**Comment by emavgl** [comment]
Which error do you get?

**Comment by raulsorrentino** [comment]
Error Details:

When attempting to build, I receive the following error:

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/Users/raulsorrentino/development/oinkoin/android/app/build.gradle' line: 58

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'
```

Both failures point to the same issue in build.gradle. Any suggestions on resolving this?

**Comment by emavgl** [comment]
You need to create a file with some configuration

https://github.com/emavgl/oinkoin/blob/master/android/app/build.gradle#L49C60-L49C74

Check out the official documentation on how to create it 

https://docs.flutter.dev/deployment/android#reference-the-keystore-from-the-app

**Comment by raulsorrentino** [comment]
Hi, I created the key.properties dummy file to resolve a previous issue, but I am now encountering the following error:

```
FAILURE: Build failed with an exception.
* Where: Build file '/Users/raulsorrentino/development/oinkoin/android/build.gradle' line: 13
* What went wrong:
A problem occurred evaluating root project 'android'.
> A problem occurred configuring project ':app'.
   > Could not create task ':app:copyFlutterAssetsDevDebug'.
      > Could not create task ':app:mergeDevDebugAssets'.
         > Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```

I am using JDK 21 and had to update Gradle to version 8.9 for the project.

Should the key.properties file be required for debug builds, or is it possible that the issue lies with the dummy file? I would expect it not to be necessary for debug builds, but I can create a real one if needed.

Thanks for your help!

**Comment by raulsorrentino** [comment]
I managed to resolve the issue by switching to JDK 17, as suggested. I was able to successfully build the APK and run it without further problems. Thank you for your assistance!
