### ISSUE TITLE
Feature request: Add view for purse balance

### ISSUE THREAD

**Issue by r4dh4l** [emavgl/oinkoin#164]
Hi,

using oinkoin since August 2024 I really like the app tracking my cash flow. One thing which is a little bit distracting is to separate between tracking my money spending cashless and money spend in cash. For example: If I withdraw money at an ATM it is not part of my account anymore but not spent and in my purse.

So it would be nice to have the Income / Expense / Balance section extended in a way like this:

| Account | Income | Expenses | Balance |
| ------------ | ----------- | ------------- | ------------ |
| Bank X | 1'283.80 | -379.44 | 904.36 |
| Purse | 100 | 79.90 | 20.10 |

For this I think it needs record entries for affected account.

However: Thank you for oinkoin!

**Comment by emavgl** [comment]
Hi, I am happy you enjoy the app. Having multiple "wallets" it is possibility for the app, but it needs a lot of code rewrite and I don't think it will happen soon.

For your specific case, however, what I usually do is don't track them as expenses but keep track of them when I actually use the cash. But I know of users who like to track cash withdraw as expense and forget about how they use that cash.

**Comment by emavgl** [comment]
Please refer to this issue https://github.com/emavgl/oinkoin/issues/129 as it covers your case as well.
