### ISSUE TITLE
Truncated latest transactions

### ISSUE THREAD

**Issue by anedroid** [emavgl/oinkoin#165]
With a large amount of transactions being displayed, the latest ones get truncated, probably to save memory. Displaying all transactions since the beginning is the only way to see the non-relative account balance.

Proposed solutions:
- truncate oldest transactions and load them as scrolled down,
- display non-relative balance separately

Android version: 12, LineageOS FOSS
App version: 1.0.69 F-Droid

**Comment by emavgl** [comment]
Hi, can you please attach a screenshot? 

truncate oldest transactions and load them as scrolled down, -> it should be already like this, the records should be rendered just if you scroll-down and not all together.

**Comment by anedroid** [comment]
<table><tr><td>

![Screenshot_20241107-113902_Oinkoin](https://github.com/user-attachments/assets/86e0e18e-4890-48fb-bade-01732d4d953c)

</td><td>

![Screenshot_20241107-113843_Oinkoin](https://github.com/user-attachments/assets/350adecb-f5ec-4006-b30e-a8175617eac5)

</td></tr></table>

**Comment by anedroid** [comment]
The number of record is 446.

**Comment by emavgl** [comment]
That's totally right. It is clearly a bug. I'll have a look soon, thanks for reporting.

**Comment by emavgl** [comment]
Hi, it should be fixed in the new version which includes several new features. If possible, could you please try out [this version](https://github.com/emavgl/oinkoin/pull/166) and give me some feedback?

Please remember to do backup, store it somewhere and then install the new version, just to be safe.

**Comment by emavgl** [comment]
Fixed with https://github.com/emavgl/oinkoin/releases/tag/1.0.71 - I am closing the issue. Thanks for your help!
