### ISSUE TITLE
Heavy Lag during use

### ISSUE THREAD

**Issue by IAAJL** [emavgl/oinkoin#179]
Whenever i try to do something, there is heavy lag. It makes it unusable as a reliable finance app. The features are pretty good. But sometimes, basic input like amount does not register properly. I have to retype multiple times to enter multiple digit amounts.

The app has all the features i need. But this issue has made me switch to another app.

**Comment by IAAJL** [comment]
I have downloaded from f-droid latest build. I have checked all updates. Running on android 15.

**Comment by emavgl** [comment]
Hi, I am sorry you are experiencing issues with the app. 

What do you mean exactly by "not registered properly"? You have issue when typing a number with multiple digits, or the record does not save properly?

Would it be possible to register a video? 

I have tried the F-Droid version myself, but I am unable to replicate any issue.

To other users ending up in this issue: does anyone have any lags?

**Comment by IAAJL** [comment]
Issue is if I am typing the amount, say 15. If i type fast, sometimes only 1 will be registered. 5 does not enter no matter what i type. Clicks don't register. The app kind of freezes. I have to clear it and retype the whole amount.

**Comment by emavgl** [comment]
I see. Just wondering, which Keyboard are you using? And could you try with another Keyboard?

**Comment by IAAJL** [comment]
I was using Floriskeyboard. Just tried a different one. Fossify keyboard.

It worked fine. Guess it is a keyboard issue. 

What might be the cause? It is an open source keyboard. I can raise an issue there.

**Comment by emavgl** [comment]
> I was using Floriskeyboard. Just tried a different one. Fossify keyboard.
> 
> It worked fine. Guess it is a keyboard issue. 
> 
> What might be the cause? It is an open source keyboard. I can raise an issue there.

Yes, I remember another user having issues with this Keyboard as well. However I can't find the issue, they probably have contacted me via email. 

Oinkoin uses Standard Flutter input components.

Feel free to open an issue on their page.
