### ISSUE TITLE
UX improvement: Grouping separator in one setting

### ISSUE THREAD

**Issue by DSiekmeier** [emavgl/oinkoin#18]
First, thanks for this promising app. I have a small recommendation for the Settings dialog.

Instead of using two separate settings for the Grouping separator ("Activate / Deactivate" and the Dropdown menu) it would be more intuituve if

- the Dropdown list is visible only when "Use 'Grouping separator'" is active

or

- There is only a single dropdown with the entries "none", "dot", "space", ....

**Comment by emavgl** [comment]
Hi @DSiekmeier, I am happy you like the app :) and thanks for the feedback, it is really a good point. I would go for the first option. :)

**Comment by emavgl** [comment]
Option 1 in the new version: https://github.com/emavgl/oinkoin/releases/tag/1.0.26
Preview will also be nice, but I think I need to rethink a bit where to put it. I will keep in mind if I end up reworking that page. For now I am closing this issue. Thanks for the feedback.
