### ISSUE TITLE
Please add polish language

### ISSUE THREAD

**Issue by Smuuuko** [emavgl/oinkoin#181]
Already requested on Crowdin (2 times) with no response, so here is pl json file. :)

[pl_PL.json](https://github.com/user-attachments/files/18053907/pl_PL.json)

{
  "Add a new 'Expense' category": "Dodaj nową kategorię 'Wydatki'",
  "Add a new 'Income' category": "Dodaj nową kategorię 'Dochody'",
  "Add a new category": "Dodaj nową kategorię",
  "Add a new record": "Dodaj nowy wpis",
  "Add a note": "Dodaj notatkę",
  "Add recurrent expenses": "Dodaj wydatki cykliczne",
  "All records": "Wszystkie wpisy",
  "All the data has been deleted": "Wszystkie dane zostały usunięte",
  "Amount": "Kwota",
  "App protected by PIN or biometric check": "Aplikacja chroniona kodem PIN lub weryfikacją biometryczną",
  "Archive": "Archiwum",
  "Archived Categories": "Zarchiwizowane kategorie",
  "Archiving the category you will NOT remove the associated records": "Archiwizując kategorię, nie usuniesz powiązanych wpisów",
  "Authenticate to access the app": "Zautoryzuj, aby uzyskać dostęp do aplikacji",
  "Automatic backup retention": "Automatyczne przechowywanie kopii zapasowych",
  "Available on Oinkoin Pro": "Dostępne w Oinkoin Pro",
  "Average": "Średnia",
  "Backup": "Kopia zapasowa",
  "Backup encryption": "Szyfrowanie kopii zapasowej",
  "Backup/Restore the application data": "Kopia zapasowa/Odzyskiwanie danych aplikacji",
  "Balance": "Saldo",
  "Can't decrypt without a password": "Nie można odszyfrować bez hasła",
  "Cancel": "Anuluj",
  "Categories": "Kategorie",
  "Category name": "Nazwa kategorii",
  "Choose a color": "Wybierz kolor",
  "Clicking the button below you can send us a feedback email. Your feedback is very appreciated and will help us to grow!": "Klikając przycisk poniżej, możesz wysłać nam e-mail z opinią. Twoja opinia jest dla nas bardzo cenna i pomoże nam się rozwijać!",
  "Color": "Kolor",
  "Colors": "Kolory",
  "Create backup and change settings": "Utwórz kopię zapasową i zmień ustawienia",
  "Critical action": "Krytyczna akcja",
  "Customization": "Dostosowanie",
  "DOWNLOAD IT NOW!": "POBIERZ TERAZ!",
  "Dark": "Ciemny",
  "Data is deleted": "Dane zostały usunięte",
  "Date Range": "Zakres dat",
  "Day": "Dzień",
  "Decimal digits": "Cyfry dziesiętne",
  "Decimal separator": "Separator dziesiętny",
  "Default": "Domyślny",
  "Define the records to show in the app homepage": "Zdefiniuj wpisy do wyświetlenia na stronie głównej aplikacji",
  "Delete": "Usuń",
  "Delete all the data": "Usuń wszystkie dane",
  "Deleting the category you will remove all the associated records": "Usunięcie kategorii spowoduje usunięcie wszystkich powiązanych wpisów",
  "Destination folder": "Folder docelowy",
  "Dismiss": "Odrzuć",
  "Do you really want to archive the category?": "Czy na pewno chcesz zarchiwizować kategorię?",
  "Do you really want to delete all the data?": "Czy na pewno chcesz usunąć wszystkie dane?",
  "Do you really want to delete the category?": "Czy na pewno chcesz usunąć kategorię?",
  "Do you really want to delete this record?": "Czy na pewno chcesz usunąć ten wpis?",
  "Do you really want to delete this recurrent record?": "Czy na pewno chcesz usunąć ten wpis cykliczny?",
  "Do you really want to unarchive the category?": "Czy na pewno chcesz przywrócić kategorię?",
  "Edit category": "Edytuj kategorię",
  "Edit record": "Edytuj wpis",
  "Enable automatic backup": "Włącz automatyczne kopie zapasowe",
  "Enable if you want to have encrypted backups": "Włącz, aby szyfrować kopie zapasowe",
  "Enable record's name suggestions": "Włącz sugestie nazw wpisów",
  "Enable to automatic backup at every access": "Włącz automatyczną kopię zapasową przy każdym dostępie",
  "Enter an encryption password": "Wprowadź hasło szyfrowania",
  "Enter decryption password": "Wprowadź hasło odszyfrowania",
  "Enter your password here": "Wprowadź swoje hasło tutaj",
  "Entries for category: ": "Wpisy dla kategorii: ",
  "Entries grouped by category": "Wpisy pogrupowane według kategorii",
  "Every day": "Codziennie",
  "Every four months": "Co cztery miesiące",
  "Every month": "Co miesiąc",
  "Every three months": "Co trzy miesiące",
  "Every two weeks": "Co dwa tygodnie",
  "Every week": "Co tydzień",
  "Every year": "Co rok",
  "Expenses": "Wydatki",
  "Export Backup": "Eksportuj kopię zapasową",
  "Export CSV": "Eksportuj CSV",
  "Feedback": "Opinie",
  "File will have an unique name": "Plik będzie miał unikalną nazwę",
  "Filter records by year or custom date range": "Filtruj wpisy według roku lub niestandardowego zakresu dat",
  "Food": "Jedzenie",
  "Full category icon pack and color picker": "Pełny zestaw ikon kategorii i wybór koloru",
  "Grouping separator": "Separator grupowania",
  "Home": "Strona główna",
  "Homepage time interval": "Interwał czasowy na stronie głównej",
  "House": "Dom",
  "How long do you want to keep backups": "Jak długo chcesz przechowywać kopie zapasowe",
  "Icon": "Ikona",
  "If enabled, you get suggestions when typing the record's name": "Jeśli włączone, otrzymasz sugestie podczas wpisywania nazwy wpisu",
  "Include version and date in the name": "Uwzględnij wersję i datę w nazwie",
  "Income": "Dochód",
  "Info": "Informacje",
  "It appears the file has been encrypted. Enter the password:": "Wygląda na to, że plik został zaszyfrowany. Wprowadź hasło:",
  "Language": "Język",
  "Last Used": "Ostatnio używane",
  "Last backup: ": "Ostatnia kopia zapasowa: ",
  "Light": "Jasny",
  "Load": "Załaduj",
  "Make it default": "Ustaw jako domyślne",
  "Make sure you have the latest version of the app. If so, the backup file may be corrupted.": "Upewnij się, że masz najnowszą wersję aplikacji. Jeśli tak, plik kopii zapasowej może być uszkodzony.",
  "Max": "Max",
  "Min": "Min",
  "Month": "Miesiąc",
  "Monthly": "Miesięcznie",
  "Monthly Image": "Obraz miesięczny",
  "Most Used": "Najczęściej używane",
  "Name": "Nazwa",
  "Never delete": "Nigdy nie usuwaj",
  "No": "Nie",
  "No Category is set yet.": "Nie ustawiono jeszcze kategorii.",
  "No categories yet.": "Brak kategorii.",
  "No entries to show.": "Brak wpisów do wyświetlenia.",
  "No entries yet.": "Brak wpisów.",
  "No recurrent records yet.": "Brak cyklicznych wpisów.",
  "Not a valid format (use for example: %s)": "Nieprawidłowy format (użyj na przykład: %s)",
  "Not repeat": "Nie powtarzaj",
  "OK": "OK",
  "Oinkoin Pro": "Oinkoin Pro",
  "Once set, you can't see the password": "Po ustawieniu nie możesz zobaczyć hasła",
  "Order by": "Sortuj według",
  "Original Order": "Oryginalna kolejność",
  "Others": "Inne",
  "Overwrite the key `comma`": "Nadpisz klawisz `przecinek`",
  "Overwrite the key `dot`": "Nadpisz klawisz `kropka`",
  "Password": "Hasło",
  "Please enter a value": "Proszę wprowadzić wartość",
  "Please enter the category name": "Proszę wprowadzić nazwę kategorii",
  "Privacy policy and credits": "Polityka prywatności i informacje o autorach",
  "Protect access to the app": "Chroń dostęp do aplikacji",
  "Record name": "Nazwa wpisu",
  "Records of the current month": "Wpisy bieżącego miesiąca",
  "Records of the current year": "Wpisy bieżącego roku",
  "Recurrent Records": "Wpisy cykliczne",
  "Require App restart": "Wymaga ponownego uruchomienia aplikacji",
  "Reset to default dates": "Resetuj do domyślnych dat",
  "Restore Backup": "Przywróć kopię zapasową",
  "Restore all the default configurations": "Przywróć wszystkie domyślne konfiguracje",
  "Restore data from a backup file": "Przywróć dane z pliku kopii zapasowej",
  "Restore successful": "Przywracanie zakończone sukcesem",
  "Restore unsuccessful": "Przywracanie nieudane",
  "Salary": "Wynagrodzenie",
  "Save": "Zapisz",
  "Select the app language": "Wybierz język aplikacji",
  "Select the app theme color": "Wybierz kolor motywu aplikacji",
  "Select the app theme style": "Wybierz styl motywu aplikacji",
  "Select the category": "Wybierz kategorię",
  "Select the decimal separator": "Wybierz separator dziesiętny",
  "Select the grouping separator": "Wybierz separator grupowania",
  "Select the number of decimal digits": "Wybierz liczbę cyfr dziesiętnych",
  "Send a feedback": "Wyślij opinię",
  "Send us a feedback": "Wyślij nam opinię",
  "Settings": "Ustawienia",
  "Share the backup file": "Udostępnij plik kopii zapasowej",
  "Show active categories": "Pokaż aktywne kategorie",
  "Show archived categories": "Pokaż zarchiwizowane kategorie",
  "Shows records per": "Pokazuje wpisy według",
  "Store the Backup on disk": "Zapisz kopię zapasową na dysku",
  "Sum": "Suma",
  "System": "System",
  "The data from the backup file are now restored.": "Dane z pliku kopii zapasowej zostały przywrócone.",
  "Theme style": "Styl motywu",
  "Transport": "Transport",
  "Trend in": "Trend w",
  "Unable to create a backup: please, delete manually the old backup": "Nie można utworzyć kopii zapasowej: proszę, usuń ręcznie starą kopię zapasową",
  "Unarchive": "Przywróć z archiwum",
  "Upgrade to": "Uaktualnij do",
  "Upgrade to Pro": "Uaktualnij do Pro",
  "View or delete recurrent records": "Wyświetl lub usuń wpisy cykliczne",
  "Visual settings and more": "Ustawienia wizualne i inne",
  "Weekly": "Tygodniowo",
  "When typing `comma`, it types `dot` instead": "Podczas wpisywania `przecinka`, w zamian wpisuje `kropkę`",
  "When typing `dot`, it types `comma` instead": "Podczas wpisywania `kropki`, w zamian wpisuje `przecinek`",
  "Year": "Rok",
  "Yes": "Tak",
  "You need to set a category first. Go to Category tab and add a new category.": "Musisz najpierw ustawić kategorię. Przejdź do zakładki Kategoria i dodaj nową kategorię.",
  "apostrophe": "apostrof",
  "comma": "przecinek",
  "dot": "kropka",
  "none": "brak",
  "space": "spacja",
  "underscore": "podkreślenie"
}

**Comment by emavgl** [comment]
Hi! Strangely enough I haven't received any notification on Crowdin. I will have a look tomorrow morning. Thanks you so much for contributing! :)

**Comment by emavgl** [comment]
Added, also gave you credits on the readme :)

It will be on the next release :)
