### ISSUE TITLE
UX improvement: Show the app version somewhere

### ISSUE THREAD

**Issue by DSiekmeier** [emavgl/oinkoin#20]
Currently I can't find a place where to get the used app version.

Having this would make it more comfortable for the user to submit more detailed bug reports and / or feature requests.

**Comment by emavgl** [comment]
Also good point. I will integrate this somewhere in the settings, also, when sending an feedback email.

**Comment by emavgl** [comment]
Added in https://github.com/emavgl/oinkoin/releases/tag/1.0.26 - you can find in the Feedback page. Also will be included when sending an email.
