### ISSUE TITLE
Feature Request: German translation

### ISSUE THREAD

**Issue by DSiekmeier** [emavgl/oinkoin#22]
For the german speaking users a translation is currently missing.

Me personally I would like to participate on this topic! If you can give me a couple of days to make myself acquainted with the project, I would be glad to create a Pull request for you.

**Comment by emavgl** [comment]
Thank you @DSiekmeier, that would be very very much appreciated. I have explained how to add the German translation in this post: https://github.com/emavgl/oinkoin/issues/3#issuecomment-1822660006

But it may easily get complicated, maybe I would create a small python scripts that could help you figure out which strings are missing to be translated.

Let me know how can I help you with that.

**Comment by DSiekmeier** [comment]
Yes, I saw that post before, thanks.

It has been a while since I implemented something in Python so I guess I will go a "manual" way first and see how far I get.

**Comment by DSiekmeier** [comment]
Working on this here: #24

**Comment by emavgl** [comment]
Thanks for the contribution. I'll add the python script myself. Eventually, I would like to migrate the dictionary in the .i18n files into JSONs. But for now you can start with changing those files manually.

**Comment by emavgl** [comment]
In the newest release https://github.com/emavgl/oinkoin/releases/tag/1.0.28

Closing the ticket. In case you can still comment here, or follow-up in the [discussion](https://github.com/emavgl/oinkoin/discussions/29) for the 1.0.28.

Thanks again!

**Comment by emavgl** [comment]
Hi @DSiekmeier, I have recently added an integration with the platform Crowdin for the translation. It should facilitate the translations of new strings. You can find the link here https://github.com/emavgl/oinkoin#translation - let me know if there are any issue (login etc)

**Comment by DSiekmeier** [comment]
Thanks for the information! @emavgl

I did not have a look yet how to use that platform, but at least login is working fine. 🙂
