### ISSUE TITLE
Feature Request: sorting categories

### ISSUE THREAD

**Issue by nizarus** [emavgl/oinkoin#25]
Hi,
Actually categories are displayed by the order of creation on the "Select the category" pane. It would be great if we can sort them in deferent orders. For example:
- Last used
- Most used
- Alphabetically

**Comment by emavgl** [comment]
Very good idea, thanks for the feedback!

**Comment by emavgl** [comment]
Hi, sorting is implemented in the new version, which is currently in development (beta). If possible, could you please try out [this version]((https://github.com/emavgl/oinkoin/pull/166) and give me some feedback?

Please remember to do backup, store it somewhere and then install the new version, just to be safe.

**Comment by nizarus** [comment]
Hi @emavgl,
Sorry, but I no longer using oinkoin. I switched to another application.
Keep the good work.

**Comment by emavgl** [comment]
Fixed with https://github.com/emavgl/oinkoin/releases/tag/1.0.71 - I am closing the issue. Thanks for your help!
