### ISSUE TITLE
Add Multi-Language Support

### ISSUE THREAD

**Issue by StefanoBerlato** [emavgl/oinkoin#3]
As per title, I would start thinking about multi-language support, if you are ok I can take care of it.

**Comment by freacore** [comment]
What files exactly do I have to translate? Because there is no german or spanish available yet.

**Comment by nizarus** [comment]
Hi,
Why not using a translation platform like https://weblate.org/ so the application can be translated by the community in multiple languages

**Comment by emavgl** [comment]
Thanks, I am not familiar with weblate and I will look at it, together with crowdin. The format used in this app is not a standard and it can be of difficult integration. So I was thinking to put all the strings in a single file like en.json, it.json, de.json and so on. Then those websites should be able to work with them.

**Comment by emavgl** [comment]
Hi there, I have recently added an integration with the platform Crowdin for the translation. It should facilitate the translations of new strings. You can find the link here https://github.com/emavgl/oinkoin#translation - let me know if there are any issue (login etc)

cc: @nizarus @freacore

**Comment by nizarus** [comment]
I can help in French and Arabic translation. Please activate them in Crowdin.

**Comment by emavgl** [comment]
@nizarus just added :) do you require any additional permissions?

**Comment by nizarus** [comment]
@emavgl done 👍

**Comment by emavgl** [comment]
Thank you so much @nizarus - I have released a new version and it got already approved in Google Play. You can find your translation in https://github.com/emavgl/oinkoin/releases/tag/1.0.31

**Comment by nizarus** [comment]
I detected a wrong French translation and I updated it on Crowdin.
Also the format in 'Recurrent Records' pane should be updated to display the whole message. See :
![Screenshot_2023-12-18-10-46-21-61_0f5c2f5270a23bdff84fc4b805035205](https://github.com/emavgl/oinkoin/assets/17108772/49cddd74-7c84-4608-aecd-d62a07ab7146)

**Comment by emavgl** [comment]
Thanks, merged with the PR https://github.com/emavgl/oinkoin/pull/38
They will be released, together with the 'Recurrent Records' pane in the next release :)

**Comment by emavgl** [comment]
I have created the following threads on Github discussions page: https://github.com/emavgl/oinkoin/discussions/categories/translations - so that we leave this issue closed, and we have always going discussions there.
