### ISSUE TITLE
Feature Request: Permanent balance

### ISSUE THREAD

**Issue by em2ka12sa** [emavgl/oinkoin#31]
Hi, I would like a setting that allows you to leave the same balance after the new month, so that in the new month my balance remains the same as at the end of last month, without changing to zero. I also wanted the "Shows records per" function to be able to save the selected value after restarting the application – I select the display for the whole year, close the application and open it again, my records are also shown for the whole year. I think at least one of these things will be quite useful.

**Comment by emavgl** [comment]
Hi,

Thanks for the feedback. They are both valid feature requests. For the first point, would you like to move to the next month just the balance or also the sum of the expenses/incomes?

**Comment by em2ka12sa** [comment]
As for the first function, I would like only the balance to move.

As for the second function, I do not think that it is necessary to save the value of a certain time range, it would be enough to save the choice between displaying for a month and for a year.

**Comment by em2ka12sa** [comment]
Oh sorry
