### ISSUE TITLE
Bug: Repeating transaction record is added on each page update

### ISSUE THREAD

**Issue by m-fedorov-s** [emavgl/oinkoin#53]
After adding a repeating transaction with a one week period, I have one record added on each reload of the main page. The records just accumulate indefinitely. However, if the repeating period is one day, then the bug does not reproduce.
I would guess that the bug is on the following line:
https://github.com/emavgl/oinkoin/blob/54e293bffbd4f92ef66db4b4646db1023aa0e477/lib/services/recurrent-record-service.dart#L47
Should we use lastUpdate time instead of startTime (similarly to the each day pattern)?
I am not familiar with the codebase, so it is just a guess.

Version: com.github.emavgl.piggybankpro-1.0.34
(Installed from f-droid)

Screenshot:
![IMG_20240104_135130](https://github.com/emavgl/oinkoin/assets/32868817/2cf30f55-443a-4370-b6b9-de095aece27c)

**Comment by emavgl** [comment]
Hello, thank you so much for reporting the bug and thanks for looking also at the code spotting the bug.

I think that line is the problem, unfortunately I am out from my PC at the moment.

I'll fix as soon as possible, in the next few days. Sorry for the inconvenience

**Comment by emavgl** [comment]
Hi there,

I have changed the lines and tested locally, it should be good by now, but if you could test it would be better.

The changes is in commit: https://github.com/emavgl/oinkoin/commit/0920cd8bb63c2d37de1c3dba94705459151f351f
There is already a new release with the change: https://github.com/emavgl/oinkoin/releases/tag/1.0.35

**Comment by m-fedorov-s** [comment]
> Hi there,
> 
> I have changed the lines and tested locally, it should be good by now, but if you could test it would be better.
> 
> The changes is in commit: [0920cd8](https://github.com/emavgl/oinkoin/commit/0920cd8bb63c2d37de1c3dba94705459151f351f) There is already a new release with the change: https://github.com/emavgl/oinkoin/releases/tag/1.0.35

Hello,
The changes look good. I tested the new release, the bug didn’t reproduce. Thank you!

**Comment by emavgl** [comment]
Perfect, thanks for trying and again for reporting.

I am closing the issue
