### ISSUE TITLE
Bug: Problem inserting record due to missing Eastern Arabic numbers support

### ISSUE THREAD

**Issue by emavgl** [emavgl/oinkoin#56]
I have recevived the following email:

> So my device language is Farsi but I can't change the language of the displayed keyboard and apparently the app thinks I should enter Farsi numbers and shows me invalid input error as captured below.
> Is there anything I can do to fix this?

![Screenshot_۲۰۲۴-۰۱-۰۵-۲۰-۲۷-۵۷-۵۳۶_com github emavgl piggybankpro](https://github.com/emavgl/oinkoin/assets/6958722/bb3c742a-21ad-46db-8dc2-8508270f3d68)

At the moment, I am calling the keyboard with inputType=phone. This is because I would like the default keyboard to have symbols like +, -, * to perform simple mathematical operations.

However, here it seems that the keyboard comes with Arabic numbers, and does not give the possibility to provide the [Eastern Arabic numbers](https://en.wikipedia.org/wiki/Eastern_Arabic_numerals) instead. 

I see two possibilities here:

- Force the app to switch to a EN_US locale, for those problematic locales with eastern arabic numbers.
- Maybe switching the keyboard_type to `numbers` may include also those Eastern Arabic numbers as well.

@nizarus, do you maybe know something more about this number format?

**Comment by nizarus** [comment]
Hi @emavgl,
Can't reproduce this issue with Arabic locales, even with countries using eastern Arabic numbers.
I'm not an android developer so I don't know if there is a more suitable inputType in this case.
But if I take the case of the equivalent application that I was using [MoneyWallet](https://github.com/AndreAle94/moneywallet), this application is using a calculator as input interface (screen shot attached)
![Screenshot_2024-01-08-13-27-02-57_c4591ddf344e7a3ac352a2553c81405a](https://github.com/emavgl/oinkoin/assets/17108772/1c1b3e8f-68bc-4534-a8b6-2bf34c5c39b5)

**Comment by emavgl** [comment]
Addressed in https://github.com/emavgl/oinkoin/releases/tag/1.0.39

I have added a check, if the Locale does not uses https://en.wikipedia.org/wiki/Arabic_numerals then it will default to en_US locale.

I could not find a better solution at the moment, closing until a better solution is found.
