### ISSUE TITLE
Display for all time

### ISSUE THREAD

**Issue by em2ka12sa** [emavgl/oinkoin#69]
Hi, I would like the "Shows records per" selection menu to have a feature for displaying deposits/expenses for all time. Also, if you select this display option, the display mode will remain after restarting the application. Right now, when I select to display deposits/expenses for a certain month or year, after restarting, the display resets to the current month

**Comment by emavgl** [comment]
Hi there, I have added this feature in https://github.com/emavgl/oinkoin/releases/tag/1.0.58
If you now go to Settings > Customization you will find a setting where you can set the data interval for the homepage. 

Three options are available:hi
- Current month (the default option)
- Current year
- All records 

I am closing this issue, but feel free to try this feature, comment or re-open the issue if needed. Have a nice day!
