### ISSUE TITLE
Offering Chinese support

### ISSUE THREAD

**Issue by Chzy2018** [emavgl/oinkoin#73]
A really simple but efficient app that helps me a lot! It's a pity that I didn't find Chinese in language options. So I wish to offer Chinese language support to the program so that more Chinese users can get access to this great app.

**Comment by emavgl** [comment]
Hi there, I am happy you like the app. I'd be happy to offer the app in Chinese as well. Unfortunately I don't know Chinese myself, along with most of the other languages. That's why Oinkoin relies on its users to help with the translations. Have a look here
 https://github.com/emavgl/oinkoin#translation

If you are interested in contributing with Chinese, I can enable the language on Crowdin platform.

**Comment by Chzy2018** [comment]
Oh, yes, I am very happy to provide Chinese translation for this app and share it with Chinese friends.

You can enable the Chinese langage on Crowdin. I will try my best to contribute on the translation.

**Comment by Chzy2018** [comment]
In fact most people in mainland China use Simplified Chinese. Traditional Chinese is only widely used in Hong Kong, Macau, Taiwan and some neighboring areas. To tell the truth, I'm not particularly familiar with Traditional Chinese either, but I can try my best to translate both.

**Comment by emavgl** [comment]
I understand, thank you for the explanation. Please, do just whatever you are comfortable too. Simplified Chinese will be a very first good start. Thank you so much for contributing. Also, feel free to leave the PR opened, in case you have questions and so on.

**Comment by Chzy2018** [comment]
I have completed the simplified Chinese translation of most of the words in the app and  made every effort to ensure that their meanings were not misrepresented. However, I was not able to locate the remaining words in the app, so not attempted to translate them. I hope you can tell me the exact location of these words in the app so that I can understand their meanings, thank you!

**Comment by emavgl** [comment]
Thank you, you are super fast! I have added a screenshot with context for "Dismiss", please ignore the rest of the strings that are not used anymore in the app and will be removed.

**Comment by Chzy2018** [comment]
OK, thanks. I have finished the context of "Dismiss". You can integrate these translations in the next version of the app now!

**Comment by emavgl** [comment]
Ok, just one thing. Do Chinese use the [Arabic numbers](https://en.wikipedia.org/wiki/Arabic_numerals), correct? At the moment Oinkoin does not support any other numerals.

**Comment by Chzy2018** [comment]
Yes, Chinese use Arabic numbers in most cases.

**Comment by emavgl** [comment]
Released in [1.0.42](https://github.com/emavgl/oinkoin/releases/tag/1.0.42)
I am opening a Github discussions for future comments https://github.com/emavgl/oinkoin/discussions/78 and closing this issue. Thank you so much for your contribution.
