### ISSUE TITLE
Wrong format for Locale en_NL - Possibility to change decimal separator

### ISSUE THREAD

**Issue by mvdkleijn** [emavgl/oinkoin#75]
I'd like to be able to see

1.000,95

Instead of the current

1,000,95

i.e. dot for thousands separator and comma for cents

**Comment by emavgl** [comment]
The current format you wrote seem very strange. Probably a bug. Can you please tell me the language and region of your phone?

Please, also make sure you have the latest version of the app installed.

**Comment by mvdkleijn** [comment]
That was fast. :-)

Language English, region Netherlands. And yes latest version.

Sorry, you can forget about the example current format that's my mistake in trying to formulate the issue clearly.

What I want to have is:

1. a period / dot ('.') as an option for the grouping separator.

2. Similarly to the grouping separator override I want to be able to override the decimals separator. I.e I want to be able to select a comma to be displayed in front of the cents.

**Note**: I understand that the weird formatting I see is probably tied to the fact that I run English language and Dutch region but I know more people who do that... and the app is already half way to allowing a full override. :smile:

**Comment by emavgl** [comment]
Thanks for expanding :)

I am bit confused by your example in the first post. Is it correct that you see "commas" for both separators? In that case, it is definitely a bug.

However, I have tried it just now on my phone and the format looks like 1,234.56 - is it also what you see and therefore what was written before was a typo? :)

If you instead want to convert from 1,234.56 --> 1.234,56. 

You are right, at the moment it is not possible at all changing the decimal separator, as it requires quite a few changes for that. So you won't be able to customize it at the moment.

However, I would actually like to investigate a bit on this, since it makes sense to take the currency format from the region and not from the language. But in your case, the region seemed to be ignored instead.

**Comment by mvdkleijn** [comment]
> I am bit confused by your example in the first post. Is it correct that you see "commas" for both separators? In that case, it is definitely a bug.
> 
> However, I have tried it just now on my phone and the format looks like 1,234.56 - is it also what you see and therefore what was written before was a typo? :)

Typo, yes. Sorry. I was typing on my phone. :-p
 
> If you instead want to convert from 1,234.56 --> 1.234,56.

Exactly.

> You are right, at the moment it is not possible at all changing the decimal separator, as it requires quite a few changes for that. So you won't be able to customize it at the moment.

Ah understood. Too bad.
 
> However, I would actually like to investigate a bit on this, since it makes sense to take the currency format from the region and not from the language. But in your case, the region seemed to be ignored instead.

I don't know about that. I usually try to set specific settings in case the app allows that because my experience is that most apps relying on language and / or region settings don't produce the combination I want. (same goes for a lot of desktop stuff btw)

I use Android 13, and for to show you my exact situation, I'll attach a screenshot in a moment.

In it you'll see that general numbers in the example show as 12.345,67 however currency shows up as €1,234.56 which makes zero sense to me.

In any case, thanks for a great app that keeps it as simple as possible.

**Comment by mvdkleijn** [comment]
> However it is very funny, from the screenshot, also Android seem a bit confused with the formats. Since numbers seems using commas as separators, while currency uses dot.
> 
> So after seeing your screenshot, I am more confused on what it would be the expected behavior.

Exactly! :smile: 

Anyway, I'm not in a hurry or anything so no pressure! (and thanks!)

**Comment by emavgl** [comment]
I'll take some time for figure it out then. Thanks for reporting, and thanks for using the app. I am happy you like it :)

**Comment by DocSniper** [comment]
Same with me. Although I'm not a native, I also set all the devices I own to English.
The same thing that applies to the decimal separator also applies to the date, I prefer YYYY-MM-DD, for example 2024-01-28.
An adjustment or a manual setting option for the date format would also be great here. 
Thanks 😃

**Comment by emavgl** [comment]
Hi @mvdkleijn ,

Check the new release https://github.com/emavgl/oinkoin/releases/tag/1.0.50

You should now be able to select the format you want from the customization page. Let me know if it works for you :)

**Comment by mvdkleijn** [comment]
I triee downloading and installing the apk from Github but it refused, stating it was conflucting with my existing install.

I also noticed that this is a "pro" version whereas my existing install doesn't have that moniker?

Running 1.0.48 on Android 14 now by the way.

**Comment by emavgl** [comment]
Ok, no problem. Then wait to get an update with the way you have installed the app :)

**Comment by emavgl** [comment]
Closing the issue, as it should be solved with [1.0.50](https://github.com/emavgl/oinkoin/releases/tag/1.0.50).
