### ISSUE TITLE
No categories after deleting all data

### ISSUE THREAD

**Issue by jiru** [emavgl/oinkoin#80]
Using 1.0.44 APK release from GitHub, one should be able to reproduce this bug.

1. Clear app storage and start app.
2. Go to Categories and notice the default categories House, Transports etc.
3. Go to Settings and tap Delete, confirm deleting all data.
4. Go to Categories and notice the categories are still there.
5. Go to Home and click "+" to add a new record.
6. Bug: a dialog says that no categories are set yet.
7. Close the app and restart it.
8. Bug: go to Categories and notice there are no categories after all.

I think the excepted behavior here is that:
* The Categories screen should be updated right after "Delete all data" operation completed, reflecting the new state of the database
* The "Delete all data" operation should re-create the default categories, or maybe ask the user what they want to do with the categories.

**Comment by emavgl** [comment]
Should be fixed in https://github.com/emavgl/oinkoin/releases/tag/1.0.45

Now the categories page is refreshed when coming back from the deletion.

I am closing the issue. Please feel free to comment if something does not work.
