### ISSUE TITLE
Preselected date in calendar is always today

### ISSUE THREAD

**Issue by jiru** [emavgl/oinkoin#81]
When adding or editing a record, clicking on the date field shows a calendar to help choosing a date. This calendar is very nice however the preselected date is *always* today regardless of what the record date is currently set to. This behavior is especially awkward when editing existing records.

**Comment by emavgl** [comment]
Good idea. 

Changed in https://github.com/emavgl/oinkoin/releases/tag/1.0.45

The initial date will be the one selected in the record.
