### ISSUE TITLE
overwriting in menu

### ISSUE THREAD

**Issue by paulle** [emavgl/oinkoin#86]
![Screenshot_20240203-171830](https://github.com/emavgl/oinkoin/assets/4852079/c86c938d-f7d1-467d-a4fc-7bb9f1826a81)
Android 13, sony xperia 5 III

**Comment by emavgl** [comment]
Have you set bigger fonts at the system level?

**Comment by paulle** [comment]
Gesendet von Proton Mail für Mobilgeräte

Yes, I need this because of my bad eyes
-------- Original-Nachricht --------
Am 3. Feb. 2024, 17:32, schrieb Emanuele Viglianisi :

**Comment by emavgl** [comment]
I understand, is there any problem in other parts of the app?

**Comment by paulle** [comment]
For now it's the only one I've seen.
All experia 5 have a
Resolution, 1080 x 2520 pixels, 21:9 ratio. Don't know if this matters.

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 3. Feb. 2024, 17:36, schrieb Emanuele Viglianisi :

**Comment by emavgl** [comment]
Hi, I tried to do some improvements available in this release: https://github.com/emavgl/oinkoin/releases/tag/1.0.47 - could you maybe let me know if that works for you? In the future, there could be more improvements on the topic.

**Comment by paulle** [comment]
Installed it. Thank you.
It looks fine now.

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 4. Feb. 2024, 15:59, schrieb Emanuele Viglianisi :

**Comment by emavgl** [comment]
Super! I close this issue then. Thanks again for the reporting.
