### ISSUE TITLE
menupoint doesn't show complete

### ISSUE THREAD

**Issue by paulle** [emavgl/oinkoin#88]
I understand, is there any problem in other parts of the app?

_Originally posted by @emavgl in https://github.com/emavgl/oinkoin/issues/86#issuecomment-1925379104_

**Comment by paulle** [comment]
![Screenshot_20240207-200954](https://github.com/emavgl/oinkoin/assets/4852079/38577f56-33cb-468c-b95c-295cac75ace7)

**Comment by emavgl** [comment]
Thanks! Will have a look

**Comment by emavgl** [comment]
It is actually complete, but is showing some artifacts. I don't know from where they are coming from.

**Comment by paulle** [comment]
Will see when it's on f-droid and report. Thank you

Gesendet von Proton Mail für Android

-------- Ursprüngliche Nachricht --------
Am 16.11.24 13:20 um Emanuele Viglianisi schrieb :

**Comment by paulle** [comment]
Thank you. Now it's not truncated. It's fine now.

**Comment by emavgl** [comment]
Thanks for checking again, I am closing the issue! :)
