### ISSUE TITLE
Feature Request: Changing Date for recurring Expense

### ISSUE THREAD

**Issue by newhinton** [emavgl/oinkoin#91]
Currently it is only possible to change the amount or name of existing recurring expenses (or income)
It would also be great if it would be possible to change the date. Otherwise the user has to recreate the entire entry.

Thanks!

Edit:
Is this change as easy as changing [this](https://github.com/emavgl/oinkoin/blob/1b6ad179fcdc84270aa6b12f35d80ee901b8b210/lib/recurrent_record_patterns/view-recurrent-pattern-page.dart#L201) to a [TextFormField](https://github.com/emavgl/oinkoin/blob/1b6ad179fcdc84270aa6b12f35d80ee901b8b210/lib/recurrent_record_patterns/view-recurrent-pattern-page.dart#L111)? If so, i could try to implement this as a PR. Let me know!

**Comment by emavgl** [comment]
Hi, thanks for the PR :)

I am not exactly sure about the impact of changing the date. I will have to research it a bit better to be honest. My feeling is that it will not be a problem making that editable. If you are confortable with flutter, you are definetly welcome to give it a try :)

**Comment by newhinton** [comment]
Okay, i think this requires a deeper change. If i transplant the `onTap` from `edit-record-page.dart`, i can change the date visually. However, changing the device time does not add the new date, but the old one. I am not experienced enough with flutter to figure out why and how to fix this. Though if you want to give advice, i will try.

**Comment by emavgl** [comment]
I'd take a look once I get some free time :) thanks for giving it a try

**Comment by emavgl** [comment]
Hello, I have added this feature in https://github.com/emavgl/oinkoin/releases/tag/1.0.55

You can now modify basically eveything from a recurrent pattern, including the date. 

**An importante change:**

> Every change to the recurrent-pattern will be applied to all the records from the date of the recurrent-pattern. Therefore, if you have a recurrent-pattern with value X from 01/01/2024, and you change the value to Y. Then, all the records from 01/01/2024 will be delete and re-generated with Y as value. If you want to change the value from today on, then you will have to change the recurrent-pattern date to Today.

I am closing this issue, but feel free to keep commenting or re-opening the issue in case it is needed.

Have a nice day.
