### ISSUE TITLE
[PROPOSAL] Add Monero (XMR) wallet to collect donations

### ISSUE THREAD

**Issue by TheFuzzStone** [emavgl/oinkoin#99]
I really like your app and I want to support its development with money. But, I won't buy anything from Play Market on principle, because I don't want to support Google's monopoly.

If you add [Monero (XMR)](https://www.getmonero.org/) wallet address to the list of donation options, I will gladly pay you 10 times more for your app.

Thank you. :)

**Comment by emavgl** [comment]
Hi, I am happy you like the app :)

I have just created a new wallet and added the public address to the README file: `44LmMThH7jMgi5pGpRtQVxCXUr9tNSenhSm97g3zgXQZPS1bwMMqxSR7M7yFcbQ9uUJAwHTJ4gXENKXZdaTDopv9QU2aGni`

Thanks for any donations :)

**Comment by TheFuzzStone** [comment]
@emavgl, done :). Thanks for the cool app.
